' Red Ink Ribbon Code
' Copyright by David Rosenthal, david.rosenthal@vischer.com, where not generated by Visual Studio
' May only be used under the Red Ink License. See https://vischer.com/redink for more information.
'
' 8.2.2025

Imports Microsoft.Office.Tools.Ribbon
Imports System.Threading.Tasks

Partial Class Ribbon1

    Inherits Microsoft.Office.Tools.Ribbon.RibbonBase

    <System.Diagnostics.DebuggerNonUserCode()>
    Public Sub New(ByVal container As System.ComponentModel.IContainer)
        MyClass.New()

        'Required for Windows.Forms Class Composition Designer support
        If (container IsNot Nothing) Then
            container.Add(Me)
        End If

    End Sub

    <System.Diagnostics.DebuggerNonUserCode()>
    Public Sub New()
        MyBase.New(Globals.Factory.GetRibbonFactory())

        'This call is required by the Component Designer.
        InitializeComponent()

    End Sub

    'Component overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Component Designer
    Private components As System.ComponentModel.IContainer

    Public Const AN = "Red Ink"

    'NOTE: The following procedure is required by the Component Designer
    'It can be modified using the Component Designer.
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Me.Tab1 = Me.Factory.CreateRibbonTab
        Me.Group1 = Me.Factory.CreateRibbonGroup
        Me.Menu1 = Me.Factory.CreateRibbonMenu
        Me.RI_Primlang = Me.Factory.CreateRibbonButton
        Me.RI_SecLang = Me.Factory.CreateRibbonButton
        Me.RI_Translate = Me.Factory.CreateRibbonButton
        Me.RI_TranslateF = Me.Factory.CreateRibbonButton
        Me.RI_Correct = Me.Factory.CreateRibbonButton
        Me.RI_Improve = Me.Factory.CreateRibbonButton
        Me.RI_Shorten = Me.Factory.CreateRibbonButton
        Me.RI_Anonymize = Me.Factory.CreateRibbonButton
        Me.RI_SwitchParty = Me.Factory.CreateRibbonButton
        Me.RI_FreestyleNM = Me.Factory.CreateRibbonButton
        Me.RI_FreestyleAM = Me.Factory.CreateRibbonButton
        Me.RI_Undo = Me.Factory.CreateRibbonButton
        Me.Menu2 = Me.Factory.CreateRibbonMenu
        Me.RI_AdjustHeight = Me.Factory.CreateRibbonButton
        Me.RI_AdjustLegacyNotes = Me.Factory.CreateRibbonButton
        Me.RI_Regex = Me.Factory.CreateRibbonButton
        Me.RI_Chat = Me.Factory.CreateRibbonButton
        Me.Settings = Me.Factory.CreateRibbonButton
        Me.Group2 = Me.Factory.CreateRibbonGroup
        Me.RI_PrimLang2 = Me.Factory.CreateRibbonButton
        Me.RI_Chat2 = Me.Factory.CreateRibbonButton
        Me.RI_FreestyleNM2 = Me.Factory.CreateRibbonButton
        Me.Tab1.SuspendLayout()
        Me.Group1.SuspendLayout()
        Me.Group2.SuspendLayout()
        Me.SuspendLayout()
        '
        'Tab1
        '
        Me.Tab1.ControlId.ControlIdType = Microsoft.Office.Tools.Ribbon.RibbonControlIdType.Office
        Me.Tab1.ControlId.OfficeId = "TabHome"
        Me.Tab1.Groups.Add(Me.Group1)
        Me.Tab1.Groups.Add(Me.Group2)
        Me.Tab1.Label = "TabHome"
        Me.Tab1.Name = "Tab1"
        '
        'Group1
        '
        Me.Group1.Items.Add(Me.Menu1)
        Me.Group1.Label = "Red Ink"
        Me.Group1.Name = "Group1"
        '
        'Menu1
        '
        Me.Menu1.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge
        Me.Menu1.Image = Global.Red_Ink_for_Excel.My.Resources.Resources.Red_Ink_Logo
        Me.Menu1.Items.Add(Me.RI_Primlang)
        Me.Menu1.Items.Add(Me.RI_SecLang)
        Me.Menu1.Items.Add(Me.RI_Translate)
        Me.Menu1.Items.Add(Me.RI_TranslateF)
        Me.Menu1.Items.Add(Me.RI_Correct)
        Me.Menu1.Items.Add(Me.RI_Improve)
        Me.Menu1.Items.Add(Me.RI_Shorten)
        Me.Menu1.Items.Add(Me.RI_Anonymize)
        Me.Menu1.Items.Add(Me.RI_SwitchParty)
        Me.Menu1.Items.Add(Me.RI_FreestyleNM)
        Me.Menu1.Items.Add(Me.RI_FreestyleAM)
        Me.Menu1.Items.Add(Me.RI_Undo)
        Me.Menu1.Items.Add(Me.Menu2)
        Me.Menu1.Items.Add(Me.RI_Chat)
        Me.Menu1.Items.Add(Me.Settings)
        Me.Menu1.Label = "Task"
        Me.Menu1.Name = "Menu1"
        Me.Menu1.ShowImage = True
        Me.Menu1.SuperTip = "Access other functions of Red Ink"
        '
        'RI_Primlang
        '
        Me.RI_Primlang.Label = "English"
        Me.RI_Primlang.Name = "RI_Primlang"
        Me.RI_Primlang.OfficeImageId = "TranslateMenu"
        Me.RI_Primlang.ScreenTip = "Will translate the text in the selected cells"
        Me.RI_Primlang.ShowImage = True
        '
        'RI_SecLang
        '
        Me.RI_SecLang.Label = "German"
        Me.RI_SecLang.Name = "RI_SecLang"
        Me.RI_SecLang.OfficeImageId = "TranslateMenu"
        Me.RI_SecLang.ScreenTip = "Will translate the text in the selected cells"
        Me.RI_SecLang.ShowImage = True
        '
        'RI_Translate
        '
        Me.RI_Translate.Label = "Translate (text)"
        Me.RI_Translate.Name = "RI_Translate"
        Me.RI_Translate.OfficeImageId = "TranslateMenu"
        Me.RI_Translate.ScreenTip = "Translates the text in the selected cells into a language you choose"
        Me.RI_Translate.ShowImage = True
        '
        'RI_TranslateF
        '
        Me.RI_TranslateF.Label = "Translate (cells)"
        Me.RI_TranslateF.Name = "RI_TranslateF"
        Me.RI_TranslateF.OfficeImageId = "TranslateMenu"
        Me.RI_TranslateF.ScreenTip = "Translates the text and the formulas in the selected cells into a language you ch" &
    "oose"
        Me.RI_TranslateF.ShowImage = True
        '
        'RI_Correct
        '
        Me.RI_Correct.Label = "Correct"
        Me.RI_Correct.Name = "RI_Correct"
        Me.RI_Correct.OfficeImageId = "SpellingAndGrammar"
        Me.RI_Correct.ScreenTip = "Will correct the text in the selected cells"
        Me.RI_Correct.ShowImage = True
        '
        'RI_Improve
        '
        Me.RI_Improve.Label = "Write Neatly"
        Me.RI_Improve.Name = "RI_Improve"
        Me.RI_Improve.OfficeImageId = "BlogPublishDraft"
        Me.RI_Improve.ScreenTip = "Will rewrite the text based on keywords in the selected cells (and a context)"
        Me.RI_Improve.ShowImage = True
        '
        'RI_Shorten
        '
        Me.RI_Shorten.Label = "Shorten"
        Me.RI_Shorten.Name = "RI_Shorten"
        Me.RI_Shorten.OfficeImageId = "Cut"
        Me.RI_Shorten.ScreenTip = "Will shorten the text in the selected cells as indicated"
        Me.RI_Shorten.ShowImage = True
        '
        'RI_Anonymize
        '
        Me.RI_Anonymize.Label = "Anonymize"
        Me.RI_Anonymize.Name = "RI_Anonymize"
        Me.RI_Anonymize.OfficeImageId = "ApplyCoAuthoringLock"
        Me.RI_Anonymize.ScreenTip = "Will anonymize the text in the selected cells"
        Me.RI_Anonymize.ShowImage = True
        '
        'RI_SwitchParty
        '
        Me.RI_SwitchParty.Label = "Switch Party"
        Me.RI_SwitchParty.Name = "RI_SwitchParty"
        Me.RI_SwitchParty.OfficeImageId = "AddDepartment"
        Me.RI_SwitchParty.ScreenTip = "Will switch two parties in the text of the selected cells"
        Me.RI_SwitchParty.ShowImage = True
        '
        'RI_FreestyleNM
        '
        Me.RI_FreestyleNM.Label = "Freestyle"
        Me.RI_FreestyleNM.Name = "RI_FreestyleNM"
        Me.RI_FreestyleNM.OfficeImageId = "CustomActionsGallery"
        Me.RI_FreestyleNM.ScreenTip = "Allows you to to enter a prompt and have the result shown (and inserted)"
        Me.RI_FreestyleNM.ShowImage = True
        '
        'RI_FreestyleAM
        '
        Me.RI_FreestyleAM.Label = "Freestyle (2nd)"
        Me.RI_FreestyleAM.Name = "RI_FreestyleAM"
        Me.RI_FreestyleAM.OfficeImageId = "CustomActionsGallery"
        Me.RI_FreestyleAM.ScreenTip = "Allows you to to enter a prompt and have the result shown (and inserted) using th" &
    "e 2nd configured model, if available"
        Me.RI_FreestyleAM.ShowImage = True
        '
        'RI_Undo
        '
        Me.RI_Undo.Enabled = False
        Me.RI_Undo.Label = "Undo Last Insert"
        Me.RI_Undo.Name = "RI_Undo"
        Me.RI_Undo.OfficeImageId = "Undo"
        Me.RI_Undo.ScreenTip = "Undo the last AI insertion (the insertion cannot be repeated)"
        Me.RI_Undo.ShowImage = True
        '
        'Menu2
        '
        Me.Menu2.Items.Add(Me.RI_AdjustHeight)
        Me.Menu2.Items.Add(Me.RI_AdjustLegacyNotes)
        Me.Menu2.Items.Add(Me.RI_Regex)
        Me.Menu2.Label = "Excel Helpers"
        Me.Menu2.Name = "Menu2"
        Me.Menu2.OfficeImageId = "GalInsertAspNet"
        Me.Menu2.ScreenTip = "Provides additional useful tools in Excel (no AI used)"
        Me.Menu2.ShowImage = True
        '
        'RI_AdjustHeight
        '
        Me.RI_AdjustHeight.Label = "Adjust Cell Height"
        Me.RI_AdjustHeight.Name = "RI_AdjustHeight"
        Me.RI_AdjustHeight.OfficeImageId = "PageScaleToFitHeight"
        Me.RI_AdjustHeight.ScreenTip = "Will adjust the height of the cells, even if combined"
        Me.RI_AdjustHeight.ShowImage = True
        '
        'RI_AdjustLegacyNotes
        '
        Me.RI_AdjustLegacyNotes.Label = "Adjust Size of Notes"
        Me.RI_AdjustLegacyNotes.Name = "RI_AdjustLegacyNotes"
        Me.RI_AdjustLegacyNotes.OfficeImageId = "ShowNotesPage"
        Me.RI_AdjustLegacyNotes.ScreenTip = "Will adjust the size of any (legacy) notes used"
        Me.RI_AdjustLegacyNotes.ShowImage = True
        '
        'RI_Regex
        '
        Me.RI_Regex.Label = "Regex Search && Replace"
        Me.RI_Regex.Name = "RI_Regex"
        Me.RI_Regex.OfficeImageId = "ReplaceDialog"
        Me.RI_Regex.ScreenTip = "Will perform a RegEx search (and replace)"
        Me.RI_Regex.ShowImage = True
        '
        'RI_Chat
        '
        Me.RI_Chat.Label = "Chatbot"
        Me.RI_Chat.Name = "RI_Chat"
        Me.RI_Chat.OfficeImageId = "ContactUs"
        Me.RI_Chat.ScreenTip = "Will open a window where you can chat with the LLM"
        Me.RI_Chat.ShowImage = True
        '
        'Settings
        '
        Me.Settings.Label = "Settings"
        Me.Settings.Name = "Settings"
        Me.Settings.OfficeImageId = "SetupClassicOffline"
        Me.Settings.ScreenTip = "Allows you to temporarily change the settings"
        Me.Settings.ShowImage = True
        '
        'Group2
        '
        Me.Group2.Items.Add(Me.RI_PrimLang2)
        Me.Group2.Items.Add(Me.RI_Chat2)
        Me.Group2.Items.Add(Me.RI_FreestyleNM2)
        Me.Group2.Label = "Red Ink"
        Me.Group2.Name = "Group2"
        Me.Group2.Position = Me.Factory.RibbonPosition.AfterOfficeId("GroupNames")
        '
        'RI_PrimLang2
        '
        Me.RI_PrimLang2.Label = "English"
        Me.RI_PrimLang2.Name = "RI_PrimLang2"
        Me.RI_PrimLang2.OfficeImageId = "TranslateMenu"
        Me.RI_PrimLang2.ScreenTip = "Will translate the selected text"
        Me.RI_PrimLang2.ShowImage = True
        '
        'RI_Chat2
        '
        Me.RI_Chat2.Label = "Chatbot"
        Me.RI_Chat2.Name = "RI_Chat2"
        Me.RI_Chat2.OfficeImageId = "ContactUs"
        Me.RI_Chat2.ScreenTip = "Will open a window where you can chat with the LLM"
        Me.RI_Chat2.ShowImage = True
        '
        'RI_FreestyleNM2
        '
        Me.RI_FreestyleNM2.Label = "Freestyle"
        Me.RI_FreestyleNM2.Name = "RI_FreestyleNM2"
        Me.RI_FreestyleNM2.OfficeImageId = "CustomActionsGallery"
        Me.RI_FreestyleNM2.ScreenTip = "Allows you to to enter a prompt and have the result shown (and inserted)"
        Me.RI_FreestyleNM2.ShowImage = True
        '
        'Ribbon1
        '
        Me.Name = "Ribbon1"
        Me.RibbonType = "Microsoft.Excel.Workbook"
        Me.Tabs.Add(Me.Tab1)
        Me.Tab1.ResumeLayout(False)
        Me.Tab1.PerformLayout()
        Me.Group1.ResumeLayout(False)
        Me.Group1.PerformLayout()
        Me.Group2.ResumeLayout(False)
        Me.Group2.PerformLayout()
        Me.ResumeLayout(False)

    End Sub

    Private Async Sub Ribbon1_Load(ByVal sender As Object, ByVal e As RibbonUIEventArgs) Handles MyBase.Load
        ' Start initialization in background (asynchronously)
        Await InitializeAppAsync()
    End Sub


    Public Async Function InitializeAppAsync() As Task

        ' UI-Updates nach der Initialisierung
        Me.RI_Primlang.Label = ThisAddIn.INI_Language1 'primlang
        Me.RI_PrimLang2.Label = ThisAddIn.INI_Language1 'primlang
        Me.RI_SecLang.Label = ThisAddIn.INI_Language2 'primlang
        If Not ThisAddIn.INI_SecondAPI Then
            Me.RI_FreestyleAM.Enabled = False
        Else
            Me.RI_FreestyleAM.Enabled = True
        End If
        If Trim(ThisAddIn.INI_Language2) = "" Then
            Me.RI_SecLang.Visible = False
        Else
            Me.RI_SecLang.Visible = True
        End If
        If Trim(ThisAddIn.INI_Language1) = "" Then
            Me.RI_Primlang.Visible = False
            Me.RI_PrimLang2.Label = "(not defined)"
            Me.RI_PrimLang2.Enabled = False
        Else
            Me.RI_Primlang.Visible = True
            Me.RI_PrimLang2.Enabled = True
        End If
        Me.Menu1.ScreenTip = If(String.IsNullOrEmpty(ThisAddIn.INI_UsageRestrictions), "",
                            ThisAddIn.INI_UsageRestrictions)
        Me.Menu1.SuperTip = $"{AN} " & ThisAddIn.Version &
                        " © by David Rosenthal, VISCHER AG " &
                        "(model: " & ThisAddIn.INI_Model & ")"
        UpdateUndoButton()
    End Function

    Public Async Function UpdateUndoButton() As Task
        If ThisAddIn.undoStates Is Nothing OrElse ThisAddIn.undoStates.Count = 0 Then
            Me.RI_Undo.Enabled = False
        Else
            Me.RI_Undo.Enabled = True
        End If
    End Function


    Friend WithEvents Tab1 As Microsoft.Office.Tools.Ribbon.RibbonTab
    Friend WithEvents Group1 As Microsoft.Office.Tools.Ribbon.RibbonGroup
    Friend WithEvents RI_Correct As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents Menu1 As Microsoft.Office.Tools.Ribbon.RibbonMenu
    Friend WithEvents RI_Anonymize As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents RI_Shorten As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents RI_Improve As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents RI_Translate As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents RI_TranslateF As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents RI_Primlang As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents Group2 As Microsoft.Office.Tools.Ribbon.RibbonGroup
    Friend WithEvents RI_PrimLang2 As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents RI_Chat2 As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents Settings As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents RI_FreestyleNM As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents RI_FreestyleAM As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents RI_SecLang As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents RI_SwitchParty As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents Menu2 As Microsoft.Office.Tools.Ribbon.RibbonMenu
    Friend WithEvents RI_AdjustHeight As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents RI_AdjustLegacyNotes As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents RI_Regex As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents RI_FreestyleNM2 As Microsoft.Office.Tools.Ribbon.RibbonButton
    Friend WithEvents RI_Undo As RibbonButton
    Friend WithEvents RI_Chat As RibbonButton
End Class

Partial Class ThisRibbonCollection

    <System.Diagnostics.DebuggerNonUserCode()> _
    Friend ReadOnly Property Ribbon1() As Ribbon1
        Get
            Return Me.GetRibbon(Of Ribbon1)()
        End Get
    End Property
End Class
