' Red Ink Ribbon Code
' Copyright by David Rosenthal, david.rosenthal@vischer.com, where not generated by Visual Studio
' May only be used under the Red Ink License. See https://vischer.com/redink for more information.
'
' 8.2.2025

Imports Microsoft.Office.Tools.Ribbon
Imports System.Threading.Tasks

Partial Class Ribbon1

    Inherits RibbonBase

    <System.Diagnostics.DebuggerNonUserCode()>
    Public Sub New(ByVal container As System.ComponentModel.IContainer)
        MyClass.New()

        'Required for Windows.Forms Class Composition Designer support
        If (container IsNot Nothing) Then
            container.Add(Me)
        End If

    End Sub

    <System.Diagnostics.DebuggerNonUserCode()>
    Public Sub New()
        MyBase.New(Globals.Factory.GetRibbonFactory())

        'This call is required by the Component Designer.
        InitializeComponent()

    End Sub

    'Component overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Component Designer
    Private components As System.ComponentModel.IContainer

    Public Const AN As String = "Red Ink"


    'NOTE: The following procedure is required by the Component Designer
    'It can be modified using the Component Designer.
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Dim RibbonDialogLauncherImpl1 As Microsoft.Office.Tools.Ribbon.RibbonDialogLauncher = Me.Factory.CreateRibbonDialogLauncher
        Me.Tab1 = Me.Factory.CreateRibbonTab
        Me.Group1 = Me.Factory.CreateRibbonGroup
        Me.Menu1 = Me.Factory.CreateRibbonMenu
        Me.RI_Primlang = Me.Factory.CreateRibbonButton
        Me.RI_SecLang = Me.Factory.CreateRibbonButton
        Me.RI_Translate = Me.Factory.CreateRibbonButton
        Me.RI_Correct = Me.Factory.CreateRibbonButton
        Me.Menu4 = Me.Factory.CreateRibbonMenu
        Me.RI_Improve = Me.Factory.CreateRibbonButton
        Me.RI_NoFillers = Me.Factory.CreateRibbonButton
        Me.RI_Friendly = Me.Factory.CreateRibbonButton
        Me.RI_Convincing = Me.Factory.CreateRibbonButton
        Me.RI_BalloonMergePart = Me.Factory.CreateRibbonButton
        Me.RI_BalloonMergeFull = Me.Factory.CreateRibbonButton
        Me.RI_BalloonMergePartPrompt = Me.Factory.CreateRibbonButton
        Me.RI_BalloonMergeFullPrompt = Me.Factory.CreateRibbonButton
        Me.RI_Shorten = Me.Factory.CreateRibbonButton
        Me.RI_Anonymize = Me.Factory.CreateRibbonButton
        Me.RI_SwitchParty = Me.Factory.CreateRibbonButton
        Me.Menu3 = Me.Factory.CreateRibbonMenu
        Me.RI_Summarize = Me.Factory.CreateRibbonButton
        Me.RI_Explain = Me.Factory.CreateRibbonButton
        Me.RI_SuggestTitles = Me.Factory.CreateRibbonButton
        Me.RI_SpecialModel = Me.Factory.CreateRibbonButton
        Me.RI_CreatePodcast = Me.Factory.CreateRibbonButton
        Me.RI_CreateAudio = Me.Factory.CreateRibbonButton
        Me.RI_Anonymization = Me.Factory.CreateRibbonButton
        Me.RI_FreestyleNM = Me.Factory.CreateRibbonButton
        Me.RI_FreestyleAM = Me.Factory.CreateRibbonButton
        Me.RI_FreestyleRepeat = Me.Factory.CreateRibbonButton
        Me.RI_Search = Me.Factory.CreateRibbonButton
        Me.Menu2 = Me.Factory.CreateRibbonMenu
        Me.RI_Halves = Me.Factory.CreateRibbonButton
        Me.RI_AcceptFormat = Me.Factory.CreateRibbonButton
        Me.RI_TimeSpan = Me.Factory.CreateRibbonButton
        Me.RI_Regex = Me.Factory.CreateRibbonButton
        Me.RI_Import = Me.Factory.CreateRibbonButton
        Me.RI_InsertClipboard = Me.Factory.CreateRibbonButton
        Me.RI_Chat2 = Me.Factory.CreateRibbonButton
        Me.RI_Transcriptor = Me.Factory.CreateRibbonButton
        Me.Settings = Me.Factory.CreateRibbonButton
        Me.Group2 = Me.Factory.CreateRibbonGroup
        Me.RI_PrimLang2 = Me.Factory.CreateRibbonButton
        Me.RI_Correct2 = Me.Factory.CreateRibbonButton
        Me.RI_Chat = Me.Factory.CreateRibbonButton
        Me.Tab1.SuspendLayout()
        Me.Group1.SuspendLayout()
        Me.Group2.SuspendLayout()
        Me.SuspendLayout()
        '
        'Tab1
        '
        Me.Tab1.ControlId.ControlIdType = Microsoft.Office.Tools.Ribbon.RibbonControlIdType.Office
        Me.Tab1.ControlId.OfficeId = "TabHome"
        Me.Tab1.Groups.Add(Me.Group1)
        Me.Tab1.Groups.Add(Me.Group2)
        Me.Tab1.Label = "TabHome"
        Me.Tab1.Name = "Tab1"
        '
        'Group1
        '
        Me.Group1.Items.Add(Me.Menu1)
        Me.Group1.KeyTip = "R"
        Me.Group1.Label = "Red Ink"
        Me.Group1.Name = "Group1"
        Me.Group1.Position = Me.Factory.RibbonPosition.AfterOfficeId("GroupNames")
        '
        'Menu1
        '
        Me.Menu1.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge
        Me.Menu1.Image = Global.Red_Ink_for_Word.My.Resources.Resources.Red_Ink_Logo
        Me.Menu1.Items.Add(Me.RI_Primlang)
        Me.Menu1.Items.Add(Me.RI_SecLang)
        Me.Menu1.Items.Add(Me.RI_Translate)
        Me.Menu1.Items.Add(Me.RI_Correct)
        Me.Menu1.Items.Add(Me.Menu4)
        Me.Menu1.Items.Add(Me.RI_Shorten)
        Me.Menu1.Items.Add(Me.RI_Anonymize)
        Me.Menu1.Items.Add(Me.RI_SwitchParty)
        Me.Menu1.Items.Add(Me.Menu3)
        Me.Menu1.Items.Add(Me.RI_FreestyleNM)
        Me.Menu1.Items.Add(Me.RI_FreestyleAM)
        Me.Menu1.Items.Add(Me.RI_FreestyleRepeat)
        Me.Menu1.Items.Add(Me.RI_Search)
        Me.Menu1.Items.Add(Me.Menu2)
        Me.Menu1.Items.Add(Me.RI_Chat2)
        Me.Menu1.Items.Add(Me.RI_Transcriptor)
        Me.Menu1.Items.Add(Me.Settings)
        Me.Menu1.KeyTip = "RI"
        Me.Menu1.Label = "Task"
        Me.Menu1.Name = "Menu1"
        Me.Menu1.ShowImage = True
        Me.Menu1.SuperTip = "Access other functions of Red Ink"
        '
        'RI_Primlang
        '
        Me.RI_Primlang.KeyTip = "E"
        Me.RI_Primlang.Label = "English"
        Me.RI_Primlang.Name = "RI_Primlang"
        Me.RI_Primlang.OfficeImageId = "TranslateMenu"
        Me.RI_Primlang.ScreenTip = "Will translate the selected text"
        Me.RI_Primlang.ShowImage = True
        '
        'RI_SecLang
        '
        Me.RI_SecLang.Label = "German"
        Me.RI_SecLang.Name = "RI_SecLang"
        Me.RI_SecLang.OfficeImageId = "TranslateMenu"
        Me.RI_SecLang.ScreenTip = "Translates the selected text into a language you choose"
        Me.RI_SecLang.ShowImage = True
        '
        'RI_Translate
        '
        Me.RI_Translate.Label = "Translate"
        Me.RI_Translate.Name = "RI_Translate"
        Me.RI_Translate.OfficeImageId = "TranslateMenu"
        Me.RI_Translate.ScreenTip = "Translates the selected text into a language you choose"
        Me.RI_Translate.ShowImage = True
        '
        'RI_Correct
        '
        Me.RI_Correct.KeyTip = "C"
        Me.RI_Correct.Label = "Correct"
        Me.RI_Correct.Name = "RI_Correct"
        Me.RI_Correct.OfficeImageId = "SpellingAndGrammar"
        Me.RI_Correct.ScreenTip = "Will correct the selected text (clean and with a markup for visibility)"
        Me.RI_Correct.ShowImage = True
        '
        'Menu4
        '
        Me.Menu4.Items.Add(Me.RI_Improve)
        Me.Menu4.Items.Add(Me.RI_NoFillers)
        Me.Menu4.Items.Add(Me.RI_Friendly)
        Me.Menu4.Items.Add(Me.RI_Convincing)
        Me.Menu4.Items.Add(Me.RI_BalloonMergePart)
        Me.Menu4.Items.Add(Me.RI_BalloonMergeFull)
        Me.Menu4.Items.Add(Me.RI_BalloonMergePartPrompt)
        Me.Menu4.Items.Add(Me.RI_BalloonMergeFullPrompt)
        Me.Menu4.Label = "Improve"
        Me.Menu4.Name = "Menu4"
        Me.Menu4.OfficeImageId = "Drawing1GalleryBrightness"
        Me.Menu4.ScreenTip = "Improve your text in various ways"
        Me.Menu4.ShowImage = True
        '
        'RI_Improve
        '
        Me.RI_Improve.Label = "Improve"
        Me.RI_Improve.Name = "RI_Improve"
        Me.RI_Improve.OfficeImageId = "Drawing1GalleryBrightness"
        Me.RI_Improve.ScreenTip = "Will improve the selected text"
        Me.RI_Improve.ShowImage = True
        '
        'RI_NoFillers
        '
        Me.RI_NoFillers.Label = "No Filler Words"
        Me.RI_NoFillers.Name = "RI_NoFillers"
        Me.RI_NoFillers.OfficeImageId = "ReviewRejectChange"
        Me.RI_NoFillers.ScreenTip = "Remove filler words from your text"
        Me.RI_NoFillers.ShowImage = True
        '
        'RI_Friendly
        '
        Me.RI_Friendly.Label = "More Friendly"
        Me.RI_Friendly.Name = "RI_Friendly"
        Me.RI_Friendly.OfficeImageId = "SendCopyCheckNames"
        Me.RI_Friendly.ScreenTip = "Make your text more friendly"
        Me.RI_Friendly.ShowImage = True
        '
        'RI_Convincing
        '
        Me.RI_Convincing.Label = "More Convincing"
        Me.RI_Convincing.Name = "RI_Convincing"
        Me.RI_Convincing.OfficeImageId = "SendContactMenu"
        Me.RI_Convincing.ScreenTip = "Make your text more convincing"
        Me.RI_Convincing.ShowImage = True
        '
        'RI_BalloonMergePart
        '
        Me.RI_BalloonMergePart.Label = "Apply comment"
        Me.RI_BalloonMergePart.Name = "RI_BalloonMergePart"
        Me.RI_BalloonMergePart.OfficeImageId = "ReviewPreviousComment"
        Me.RI_BalloonMergePart.ScreenTip = "Apply the text (selected) in your comment balloon to the text in the commented pa" &
    "rt of the document"
        Me.RI_BalloonMergePart.ShowImage = True
        '
        'RI_BalloonMergeFull
        '
        Me.RI_BalloonMergeFull.Label = "Apply comment to para"
        Me.RI_BalloonMergeFull.Name = "RI_BalloonMergeFull"
        Me.RI_BalloonMergeFull.OfficeImageId = "ReviewPreviousComment"
        Me.RI_BalloonMergeFull.ScreenTip = "Apply the text (selected) in your comment balloon to the text in the commented pa" &
    "ragraph of the document"
        Me.RI_BalloonMergeFull.ShowImage = True
        '
        'RI_BalloonMergePartPrompt
        '
        Me.RI_BalloonMergePartPrompt.Label = "Apply comment (edit)"
        Me.RI_BalloonMergePartPrompt.Name = "RI_BalloonMergePartPrompt"
        Me.RI_BalloonMergePartPrompt.OfficeImageId = "ReviewEditComment"
        Me.RI_BalloonMergePartPrompt.ScreenTip = "Apply the text (selected) in your comment balloon to the text in the commented pa" &
    "ragraph of the document (you can edit the prompt)"
        Me.RI_BalloonMergePartPrompt.ShowImage = True
        '
        'RI_BalloonMergeFullPrompt
        '
        Me.RI_BalloonMergeFullPrompt.Label = "Apply comment to para (edit)"
        Me.RI_BalloonMergeFullPrompt.Name = "RI_BalloonMergeFullPrompt"
        Me.RI_BalloonMergeFullPrompt.OfficeImageId = "ReviewEditComment"
        Me.RI_BalloonMergeFullPrompt.ScreenTip = "Apply the text (selected) in your comment balloon to the text in the commented pa" &
    "ragraph of the document (you can edit the prompt)"
        Me.RI_BalloonMergeFullPrompt.ShowImage = True
        '
        'RI_Shorten
        '
        Me.RI_Shorten.Label = "Shorten"
        Me.RI_Shorten.Name = "RI_Shorten"
        Me.RI_Shorten.OfficeImageId = "Cut"
        Me.RI_Shorten.ScreenTip = "Will shorten the selected text as indicated"
        Me.RI_Shorten.ShowImage = True
        '
        'RI_Anonymize
        '
        Me.RI_Anonymize.Label = "Anonymize"
        Me.RI_Anonymize.Name = "RI_Anonymize"
        Me.RI_Anonymize.OfficeImageId = "ApplyCoAuthoringLock"
        Me.RI_Anonymize.ScreenTip = "Will anonymize the selected text"
        Me.RI_Anonymize.ShowImage = True
        '
        'RI_SwitchParty
        '
        Me.RI_SwitchParty.Label = "Switch Party"
        Me.RI_SwitchParty.Name = "RI_SwitchParty"
        Me.RI_SwitchParty.OfficeImageId = "AddDepartment"
        Me.RI_SwitchParty.ScreenTip = "Will switch two parties in your selected text"
        Me.RI_SwitchParty.ShowImage = True
        '
        'Menu3
        '
        Me.Menu3.Items.Add(Me.RI_Summarize)
        Me.Menu3.Items.Add(Me.RI_Explain)
        Me.Menu3.Items.Add(Me.RI_SuggestTitles)
        Me.Menu3.Items.Add(Me.RI_SpecialModel)
        Me.Menu3.Items.Add(Me.RI_CreatePodcast)
        Me.Menu3.Items.Add(Me.RI_CreateAudio)
        Me.Menu3.Items.Add(Me.RI_Anonymization)
        Me.Menu3.Label = "Analyze"
        Me.Menu3.Name = "Menu3"
        Me.Menu3.OfficeImageId = "PivotTableNonVisualTotals"
        Me.Menu3.ScreenTip = "Summarize, Explain, Suggest Titles and Audiotools"
        Me.Menu3.ShowImage = True
        '
        'RI_Summarize
        '
        Me.RI_Summarize.Label = "Summarize"
        Me.RI_Summarize.Name = "RI_Summarize"
        Me.RI_Summarize.OfficeImageId = "ArrangeByAvailability"
        Me.RI_Summarize.ScreenTip = "Will summarize the text your have selected"
        Me.RI_Summarize.ShowImage = True
        '
        'RI_Explain
        '
        Me.RI_Explain.Label = "Explain"
        Me.RI_Explain.Name = "RI_Explain"
        Me.RI_Explain.OfficeImageId = "About"
        Me.RI_Explain.ScreenTip = "Explain in simple terms what the selected text means"
        Me.RI_Explain.ShowImage = True
        '
        'RI_SuggestTitles
        '
        Me.RI_SuggestTitles.Label = "Suggest Titles"
        Me.RI_SuggestTitles.Name = "RI_SuggestTitles"
        Me.RI_SuggestTitles.OfficeImageId = "FillUp"
        Me.RI_SuggestTitles.ScreenTip = "Suggest various titles for the selected text"
        Me.RI_SuggestTitles.ShowImage = True
        '
        'RI_SpecialModel
        '
        Me.RI_SpecialModel.Label = "Special Service"
        Me.RI_SpecialModel.Name = "RI_SpecialModel"
        Me.RI_SpecialModel.OfficeImageId = "AutoFormatNow"
        Me.RI_SpecialModel.ScreenTip = "Query one of your special services with your selected text"
        Me.RI_SpecialModel.ShowImage = True
        '
        'RI_CreatePodcast
        '
        Me.RI_CreatePodcast.Label = "Create Podcast"
        Me.RI_CreatePodcast.Name = "RI_CreatePodcast"
        Me.RI_CreatePodcast.OfficeImageId = "IMMenu"
        Me.RI_CreatePodcast.ScreenTip = "Create a podcast of the selected text"
        Me.RI_CreatePodcast.ShowImage = True
        '
        'RI_CreateAudio
        '
        Me.RI_CreateAudio.Label = "Create Audio"
        Me.RI_CreateAudio.Name = "RI_CreateAudio"
        Me.RI_CreateAudio.OfficeImageId = "OmsInsertAudio"
        Me.RI_CreateAudio.ScreenTip = "Create an audiobook or podcast out of the text selected"
        Me.RI_CreateAudio.ShowImage = True
        '
        'RI_Anonymization
        '
        Me.RI_Anonymization.Label = "Anonymization"
        Me.RI_Anonymization.Name = "RI_Anonymization"
        Me.RI_Anonymization.OfficeImageId = "ApplyCoAuthoringLock"
        Me.RI_Anonymization.ScreenTip = "Will anonymize the selected text using local means (e.g., redink-anon.txt)"
        Me.RI_Anonymization.ShowImage = True
        '
        'RI_FreestyleNM
        '
        Me.RI_FreestyleNM.Label = "Freestyle"
        Me.RI_FreestyleNM.Name = "RI_FreestyleNM"
        Me.RI_FreestyleNM.OfficeImageId = "CustomActionsGallery"
        Me.RI_FreestyleNM.ScreenTip = "Allows you to to enter a prompt and get the result, based on selected text or wit" &
    "hout a text"
        Me.RI_FreestyleNM.ShowImage = True
        '
        'RI_FreestyleAM
        '
        Me.RI_FreestyleAM.Label = "Freestyle (2nd)"
        Me.RI_FreestyleAM.Name = "RI_FreestyleAM"
        Me.RI_FreestyleAM.OfficeImageId = "CustomActionsGallery"
        Me.RI_FreestyleAM.ScreenTip = "Allows you to to enter a prompt and get the result, based on selected text or wit" &
    "hout a text (using the 2nd configured model, if available)"
        Me.RI_FreestyleAM.ShowImage = True
        '
        'RI_FreestyleRepeat
        '
        Me.RI_FreestyleRepeat.Label = "Freestyle (redo)"
        Me.RI_FreestyleRepeat.Name = "RI_FreestyleRepeat"
        Me.RI_FreestyleRepeat.OfficeImageId = "CustomActionsGallery"
        Me.RI_FreestyleRepeat.ScreenTip = "Will repeat the last Freestyle command without prompting"
        Me.RI_FreestyleRepeat.ShowImage = True
        '
        'RI_Search
        '
        Me.RI_Search.Label = "Context Search"
        Me.RI_Search.Name = "RI_Search"
        Me.RI_Search.OfficeImageId = "Insights"
        Me.RI_Search.ScreenTip = "Allows you to search your text for information based on its meaning"
        Me.RI_Search.ShowImage = True
        '
        'Menu2
        '
        Me.Menu2.Items.Add(Me.RI_Halves)
        Me.Menu2.Items.Add(Me.RI_AcceptFormat)
        Me.Menu2.Items.Add(Me.RI_TimeSpan)
        Me.Menu2.Items.Add(Me.RI_Regex)
        Me.Menu2.Items.Add(Me.RI_Import)
        Me.Menu2.Items.Add(Me.RI_InsertClipboard)
        Me.Menu2.Label = "Word Helpers"
        Me.Menu2.Name = "Menu2"
        Me.Menu2.OfficeImageId = "GalInsertAspNet"
        Me.Menu2.ScreenTip = "Provides additional useful tools in word (no AI used)"
        Me.Menu2.ShowImage = True
        '
        'RI_Halves
        '
        Me.RI_Halves.Label = "Self-Compare Selection"
        Me.RI_Halves.Name = "RI_Halves"
        Me.RI_Halves.OfficeImageId = "ReviewCompareTwoVersions"
        Me.RI_Halves.ScreenTip = "Will compare two or more paragraphs with each other"
        Me.RI_Halves.ShowImage = True
        '
        'RI_AcceptFormat
        '
        Me.RI_AcceptFormat.Label = "Accept Format Changes"
        Me.RI_AcceptFormat.Name = "RI_AcceptFormat"
        Me.RI_AcceptFormat.OfficeImageId = "ReviewAcceptChange"
        Me.RI_AcceptFormat.ScreenTip = "Will accept all formatting changes (only them)"
        Me.RI_AcceptFormat.ShowImage = True
        '
        'RI_TimeSpan
        '
        Me.RI_TimeSpan.Label = "Markup Time Span"
        Me.RI_TimeSpan.Name = "RI_TimeSpan"
        Me.RI_TimeSpan.OfficeImageId = "ProposeNewTime"
        Me.RI_TimeSpan.ScreenTip = "Will calculate the time span between the first and the last markup/comment"
        Me.RI_TimeSpan.ShowImage = True
        '
        'RI_Regex
        '
        Me.RI_Regex.Label = "Regex Search && Replace"
        Me.RI_Regex.Name = "RI_Regex"
        Me.RI_Regex.OfficeImageId = "ReplaceDialog"
        Me.RI_Regex.ScreenTip = "Will perform a RegEx search (and replace)"
        Me.RI_Regex.ShowImage = True
        '
        'RI_Import
        '
        Me.RI_Import.Label = "Import Text File"
        Me.RI_Import.Name = "RI_Import"
        Me.RI_Import.OfficeImageId = "ImportTextFile"
        Me.RI_Import.ScreenTip = "Will insert at the current position the text of a PDF, Word document or text file" &
    ""
        Me.RI_Import.ShowImage = True
        '
        'RI_InsertClipboard
        '
        Me.RI_InsertClipboard.Label = "Clipboard to Text"
        Me.RI_InsertClipboard.Name = "RI_InsertClipboard"
        Me.RI_InsertClipboard.OfficeImageId = "ConvertInkMenu"
        Me.RI_InsertClipboard.ScreenTip = "Will convert to text what is contained in the clipboard (e.g., screenshot, video," &
    " audio, image)"
        Me.RI_InsertClipboard.ShowImage = True
        '
        'RI_Chat2
        '
        Me.RI_Chat2.Label = "Chatbot"
        Me.RI_Chat2.Name = "RI_Chat2"
        Me.RI_Chat2.OfficeImageId = "ContactUs"
        Me.RI_Chat2.ScreenTip = "Will open a window where you can chat with the LLM"
        Me.RI_Chat2.ShowImage = True
        '
        'RI_Transcriptor
        '
        Me.RI_Transcriptor.Label = "Transcriptor"
        Me.RI_Transcriptor.Name = "RI_Transcriptor"
        Me.RI_Transcriptor.OfficeImageId = "AudioRecordingInsert"
        Me.RI_Transcriptor.ShowImage = True
        '
        'Settings
        '
        Me.Settings.Label = "Settings"
        Me.Settings.Name = "Settings"
        Me.Settings.OfficeImageId = "SetupClassicOffline"
        Me.Settings.ScreenTip = "Allows you to temporarily change the settings"
        Me.Settings.ShowImage = True
        '
        'Group2
        '
        RibbonDialogLauncherImpl1.ScreenTip = "Tickle my brain, Inky!"
        Me.Group2.DialogLauncher = RibbonDialogLauncherImpl1
        Me.Group2.Items.Add(Me.RI_PrimLang2)
        Me.Group2.Items.Add(Me.RI_Correct2)
        Me.Group2.Items.Add(Me.RI_Chat)
        Me.Group2.KeyTip = "RIQ"
        Me.Group2.Label = "Red Ink"
        Me.Group2.Name = "Group2"
        Me.Group2.Position = Me.Factory.RibbonPosition.AfterOfficeId("GroupNames")
        '
        'RI_PrimLang2
        '
        Me.RI_PrimLang2.KeyTip = "E"
        Me.RI_PrimLang2.Label = "English"
        Me.RI_PrimLang2.Name = "RI_PrimLang2"
        Me.RI_PrimLang2.OfficeImageId = "TranslateMenu"
        Me.RI_PrimLang2.ScreenTip = "Will translate the selected text"
        Me.RI_PrimLang2.ShowImage = True
        '
        'RI_Correct2
        '
        Me.RI_Correct2.KeyTip = "C"
        Me.RI_Correct2.Label = "Correct"
        Me.RI_Correct2.Name = "RI_Correct2"
        Me.RI_Correct2.OfficeImageId = "SpellingAndGrammar"
        Me.RI_Correct2.ScreenTip = "Will correct the selected text"
        Me.RI_Correct2.ShowImage = True
        '
        'RI_Chat
        '
        Me.RI_Chat.Label = "Chatbot"
        Me.RI_Chat.Name = "RI_Chat"
        Me.RI_Chat.OfficeImageId = "ContactUs"
        Me.RI_Chat.ScreenTip = "Will open a window where you can chat with the LLM"
        Me.RI_Chat.ShowImage = True
        '
        'Ribbon1
        '
        Me.Name = "Ribbon1"
        Me.RibbonType = "Microsoft.Word.Document"
        Me.Tabs.Add(Me.Tab1)
        Me.Tab1.ResumeLayout(False)
        Me.Tab1.PerformLayout()
        Me.Group1.ResumeLayout(False)
        Me.Group1.PerformLayout()
        Me.Group2.ResumeLayout(False)
        Me.Group2.PerformLayout()
        Me.ResumeLayout(False)

    End Sub



    Private Async Sub Ribbon1_Load(ByVal sender As Object, ByVal e As RibbonUIEventArgs) Handles MyBase.Load
        ' Start initialization in background (asynchronously)
        Await InitializeAppAsync()

        ' Now that the .NET assemblies and everything are safely loaded,
        ' set your resource-based image here rather than in InitializeComponent.

        AddHandler RI_Correct.Click, AddressOf RI_Correct_Click
        AddHandler RI_Correct2.Click, AddressOf RI_Correct2_Click
        AddHandler RI_Summarize.Click, AddressOf RI_Summarize_Click
        AddHandler RI_Shorten.Click, AddressOf RI_Shorten_Click
        AddHandler RI_Primlang.Click, AddressOf RI_PrimLang_Click
        AddHandler RI_PrimLang2.Click, AddressOf RI_PrimLang2_Click
        AddHandler RI_SecLang.Click, AddressOf RI_SecLang_Click
        AddHandler RI_Improve.Click, AddressOf RI_Improve_Click
        AddHandler RI_FreestyleNM.Click, AddressOf RI_FreestyleNM_Click
        AddHandler RI_Anonymize.Click, AddressOf RI_Anonymize_Click
        AddHandler RI_Chat.Click, AddressOf RI_Chat_Click
        AddHandler RI_Chat2.Click, AddressOf RI_Chat2_Click
        AddHandler RI_Transcriptor.Click, AddressOf RI_Transcriptor_Click
        AddHandler RI_TimeSpan.Click, AddressOf RI_TimeSpan_Click
        AddHandler RI_AcceptFormat.Click, AddressOf RI_AcceptFormat_Click
        AddHandler RI_Halves.Click, AddressOf RI_Halves_Click
        AddHandler RI_Translate.Click, AddressOf RI_Translate_Click
        AddHandler Settings.Click, AddressOf Settings_Click
        AddHandler RI_FreestyleAM.Click, AddressOf RI_FreestyleAM_Click
        AddHandler RI_SwitchParty.Click, AddressOf RI_SwitchParty_Click
        AddHandler RI_Regex.Click, AddressOf RI_Regex_Click
        AddHandler RI_Import.Click, AddressOf RI_Import_Click
        AddHandler RI_Search.Click, AddressOf RI_Search_Click
        AddHandler RI_Explain.Click, AddressOf RI_Explain_Click
        AddHandler RI_SuggestTitles.Click, AddressOf RI_SuggestTitles_Click
        AddHandler RI_CreatePodcast.Click, AddressOf RI_CreatePodcast_Click
        AddHandler RI_CreateAudio.Click, AddressOf RI_CreateAudio_Click
        AddHandler RI_Friendly.Click, AddressOf RI_Friendly_Click
        AddHandler RI_NoFillers.Click, AddressOf RI_NoFillers_Click
        AddHandler RI_Convincing.Click, AddressOf RI_Convincing_Click
        AddHandler RI_SpecialModel.Click, AddressOf RI_SpecialModel_Click
        AddHandler RI_Anonymization.Click, AddressOf RI_Anonymization_Click
        AddHandler Group2.DialogLauncherClick, AddressOf Easteregg_Click

    End Sub

    Public Async Function InitializeAppAsync() As Task

        ' UI-Updates nach der Initialisierung
        Me.RI_Primlang.Label = ThisAddIn.INI_Language1
        Me.RI_PrimLang2.Label = ThisAddIn.INI_Language1
        Me.RI_SecLang.Label = ThisAddIn.INI_Language2
        If Not ThisAddIn.INI_SecondAPI Then
            Me.RI_FreestyleAM.Enabled = False
        Else
            Me.RI_FreestyleAM.Enabled = True
        End If
        If Trim(ThisAddIn.INI_Language2) = "" Then
            Me.RI_SecLang.Visible = False
        Else
            Me.RI_SecLang.Visible = True
        End If
        If Trim(ThisAddIn.INI_Language1) = "" Then
            Me.RI_Primlang.Visible = False
            Me.RI_PrimLang2.Label = "(not defined)"
            Me.RI_PrimLang2.Enabled = False
        Else
            Me.RI_Primlang.Visible = True
            Me.RI_PrimLang2.Enabled = True
        End If

        Dim TTS_Available As Boolean = False
        Dim IsGoogle As Boolean = False
        Dim endp As String = ThisAddIn.INI_Endpoint
        Dim endp_2 As String = ThisAddIn.INI_Endpoint_2
        Dim GoogleIdentifier As String = ThisAddIn.GoogleIdentifier
        Dim OpenAIIdentifier As String = ThisAddIn.OpenAIIdentifier

        If endp IsNot Nothing AndAlso endp.Contains(GoogleIdentifier) AndAlso ThisAddIn.INI_OAuth2 Then
            TTS_Available = True
            IsGoogle = True
        End If
        If endp_2 IsNot Nothing AndAlso endp_2.Contains(GoogleIdentifier) AndAlso ThisAddIn.INI_OAuth2_2 Then
            TTS_Available = True
            IsGoogle = True
        End If
        If endp_2 IsNot Nothing AndAlso endp_2.Contains(OpenAIIdentifier) Then
            TTS_Available = True
        End If
        If endp IsNot Nothing AndAlso endp.Contains(OpenAIIdentifier) Then
            TTS_Available = True
        End If

        If String.IsNullOrWhiteSpace(ThisAddIn.INI_APICall_Object) Then
            Me.RI_InsertClipboard.Visible = False
        Else
            Me.RI_InsertClipboard.Visible = True
        End If

        If Not TTS_Available Then
            Me.RI_CreateAudio.Visible = False
            Me.RI_CreatePodcast.Label = "Create Podcast Script"
        Else
            Me.RI_CreateAudio.Visible = True
            Me.RI_CreatePodcast.Label = "Create Podcast"
        End If

        If Trim(ThisAddIn.INI_SpeechModelPath) = "" And Not IsGoogle Then
            Me.RI_Transcriptor.Visible = False
        Else
            Me.RI_Transcriptor.Visible = True
        End If

        If Trim(ThisAddIn.INI_SpecialServicePath) = "" Then
            Me.RI_SpecialModel.Visible = False
        Else
            Me.RI_SpecialModel.Visible = True
        End If

        Dim LastFreestylePrompt As String = My.Settings.LastFreestylePrompt
        If Trim(LastFreestylePrompt) = "" Then
            Me.RI_FreestyleRepeat.Enabled = False
        Else
            Me.RI_FreestyleRepeat.Enabled = True
            If My.Settings.LastFreestyleWasAM Then
                Me.RI_FreestyleRepeat.ScreenTip = Left(My.Settings.LastFreestyleModelConfig.Model & ": " & LastFreestylePrompt, 1023)
            Else
                Me.RI_FreestyleRepeat.ScreenTip = Left(LastFreestylePrompt, 1023)
            End If
        End If

        Me.Menu1.ScreenTip = If(String.IsNullOrEmpty(ThisAddIn.INI_UsageRestrictions), "",
                            ThisAddIn.INI_UsageRestrictions)
        Me.Menu1.SuperTip = $"{AN} " & ThisAddIn.Version &
                        " © by David Rosenthal, VISCHER AG " &
                        "(model: " & ThisAddIn.INI_Model & ")"
    End Function

    Friend WithEvents Tab1 As RibbonTab
    Friend WithEvents Group1 As RibbonGroup
    Friend WithEvents RI_Correct As RibbonButton
    Friend WithEvents Menu1 As RibbonMenu
    Friend WithEvents RI_Anonymize As RibbonButton
    Friend WithEvents RI_Shorten As RibbonButton
    Friend WithEvents RI_Summarize As RibbonButton
    Friend WithEvents RI_Improve As RibbonButton
    Friend WithEvents RI_FreestyleAM As RibbonButton
    Friend WithEvents RI_Translate As RibbonButton
    Friend WithEvents RI_Primlang As RibbonButton
    Friend WithEvents Group2 As RibbonGroup
    Friend WithEvents RI_PrimLang2 As RibbonButton
    Friend WithEvents RI_Correct2 As RibbonButton
    Friend WithEvents Settings As RibbonButton
    Friend WithEvents RI_FreestyleNM As RibbonButton
    Friend WithEvents RI_Chat As RibbonButton
    Friend WithEvents RI_SecLang As RibbonButton
    Friend WithEvents RI_SwitchParty As RibbonButton
    Friend WithEvents Menu2 As RibbonMenu
    Friend WithEvents RI_Halves As RibbonButton
    Friend WithEvents RI_AcceptFormat As RibbonButton
    Friend WithEvents RI_TimeSpan As RibbonButton
    Friend WithEvents RI_Regex As RibbonButton
    Friend WithEvents RI_Import As RibbonButton
    Friend WithEvents RI_Chat2 As RibbonButton
    Friend WithEvents RI_Search As RibbonButton
    Friend WithEvents RI_Transcriptor As RibbonButton
    Friend WithEvents Menu3 As RibbonMenu
    Friend WithEvents RI_Explain As RibbonButton
    Friend WithEvents RI_SuggestTitles As RibbonButton
    Friend WithEvents RI_CreatePodcast As RibbonButton
    Friend WithEvents RI_CreateAudio As RibbonButton
    Friend WithEvents Menu4 As RibbonMenu
    Friend WithEvents RI_NoFillers As RibbonButton
    Friend WithEvents RI_Friendly As RibbonButton
    Friend WithEvents RI_Convincing As RibbonButton
    Friend WithEvents RI_SpecialModel As RibbonButton
    Friend WithEvents RI_Anonymization As RibbonButton
    Friend WithEvents RI_InsertClipboard As RibbonButton
    Friend WithEvents RI_BalloonMergePart As RibbonButton
    Friend WithEvents RI_BalloonMergeFull As RibbonButton
    Friend WithEvents RI_BalloonMergePartPrompt As RibbonButton
    Friend WithEvents RI_BalloonMergeFullPrompt As RibbonButton
    Friend WithEvents RI_FreestyleRepeat As RibbonButton
End Class

Partial Class ThisRibbonCollection

    <System.Diagnostics.DebuggerNonUserCode()> _
    Friend ReadOnly Property Ribbon1() As Ribbon1
        Get
            Return Me.GetRibbon(Of Ribbon1)()
        End Get
    End Property
End Class
