' Red Ink Ribbon Code
' Copyright by David Rosenthal, david.rosenthal@vischer.com, where not generated by Visual Studio
' May only be used under the Red Ink License. See https://vischer.com/redink for more information.
'
' 7.10.2025

Imports Microsoft.Office.Tools.Ribbon
Imports System.Threading.Tasks

Partial Class Ribbon1
    Inherits RibbonBase

    <System.Diagnostics.DebuggerNonUserCode()>
    Public Sub New(ByVal container As System.ComponentModel.IContainer)
        MyClass.New()

        'Required for Windows.Forms Class Composition Designer support
        If (container IsNot Nothing) Then
            container.Add(Me)
        End If

    End Sub

    <System.Diagnostics.DebuggerNonUserCode()>
    Public Sub New()
        MyBase.New(Globals.Factory.GetRibbonFactory())

        'This call is required by the Component Designer.
        InitializeComponent()

    End Sub

    'Component overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Component Designer
    Private components As System.ComponentModel.IContainer

    Public AN As String = "Red Ink" ' Also Search & Replace manually

    'NOTE: The following procedure is required by the Component Designer
    'It can be modified using the Component Designer.
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Me.Tab1 = Me.Factory.CreateRibbonTab
        Me.Group1 = Me.Factory.CreateRibbonGroup
        Me.Menu1 = Me.Factory.CreateRibbonMenu
        Me.RI_Primlang = Me.Factory.CreateRibbonButton
        Me.RI_Translate = Me.Factory.CreateRibbonButton
        Me.RI_Correct = Me.Factory.CreateRibbonButton
        Me.Menu2 = Me.Factory.CreateRibbonMenu
        Me.RI_Improve = Me.Factory.CreateRibbonButton
        Me.RI_ApplyMyStyle = Me.Factory.CreateRibbonButton
        Me.RI_DefineMyStyle = Me.Factory.CreateRibbonButton
        Me.RI_NoFillers = Me.Factory.CreateRibbonButton
        Me.RI_Friendly = Me.Factory.CreateRibbonButton
        Me.RI_Convincing = Me.Factory.CreateRibbonButton
        Me.RI_Shorten = Me.Factory.CreateRibbonButton
        Me.RI_Summarize = Me.Factory.CreateRibbonButton
        Me.Sumup = Me.Factory.CreateRibbonButton
        Me.RI_Answers = Me.Factory.CreateRibbonButton
        Me.RI_Freestyle = Me.Factory.CreateRibbonButton
        Me.RI_Clipboard = Me.Factory.CreateRibbonButton
        Me.Settings = Me.Factory.CreateRibbonButton
        Me.Group2 = Me.Factory.CreateRibbonGroup
        Me.RI_PrimLang2 = Me.Factory.CreateRibbonButton
        Me.RI_Correct2 = Me.Factory.CreateRibbonButton
        Me.Sumup2 = Me.Factory.CreateRibbonButton
        Me.Tab1.SuspendLayout()
        Me.Group1.SuspendLayout()
        Me.Group2.SuspendLayout()
        Me.SuspendLayout()
        '
        'Tab1
        '
        Me.Tab1.ControlId.ControlIdType = Microsoft.Office.Tools.Ribbon.RibbonControlIdType.Office
        Me.Tab1.ControlId.OfficeId = "TabNewMailMessage"
        Me.Tab1.Groups.Add(Me.Group2)
        Me.Tab1.Groups.Add(Me.Group1)
        Me.Tab1.Label = "TabNewMailMessage"
        Me.Tab1.Name = "Tab1"
        '
        'Group1
        '
        Me.Group1.Items.Add(Me.Menu1)
        Me.Group1.KeyTip = "R"
        Me.Group1.Label = "Red Ink"
        Me.Group1.Name = "Group1"
        Me.Group1.Position = Me.Factory.RibbonPosition.AfterOfficeId("GroupNames")
        '
        'Menu1
        '
        Me.Menu1.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge
        Me.Menu1.Image = Global.Red_Ink_for_Outlook.My.Resources.Resources.Red_Ink_Logo
        Me.Menu1.Items.Add(Me.RI_Primlang)
        Me.Menu1.Items.Add(Me.RI_Translate)
        Me.Menu1.Items.Add(Me.RI_Correct)
        Me.Menu1.Items.Add(Me.Menu2)
        Me.Menu1.Items.Add(Me.RI_Shorten)
        Me.Menu1.Items.Add(Me.RI_Summarize)
        Me.Menu1.Items.Add(Me.Sumup)
        Me.Menu1.Items.Add(Me.RI_Answers)
        Me.Menu1.Items.Add(Me.RI_Freestyle)
        Me.Menu1.Items.Add(Me.RI_Clipboard)
        Me.Menu1.Items.Add(Me.RI_DefineMyStyle)
        Me.Menu1.Items.Add(Me.Settings)
        Me.Menu1.KeyTip = "S"
        Me.Menu1.Label = "Task"
        Me.Menu1.Name = "Menu1"
        Me.Menu1.ShowImage = True
        Me.Menu1.SuperTip = "Access other functions of Red Ink"
        '
        'RI_Primlang
        '
        Me.RI_Primlang.KeyTip = "E"
        Me.RI_Primlang.Label = "English"
        Me.RI_Primlang.Name = "RI_Primlang"
        Me.RI_Primlang.OfficeImageId = "TranslateMenu"
        Me.RI_Primlang.ScreenTip = "Will translate the selected text"
        Me.RI_Primlang.ShowImage = True
        '
        'RI_Translate
        '
        Me.RI_Translate.Label = "Translate"
        Me.RI_Translate.Name = "RI_Translate"
        Me.RI_Translate.OfficeImageId = "TranslateMenu"
        Me.RI_Translate.ScreenTip = "Translates the selected text into a language you choose"
        Me.RI_Translate.ShowImage = True
        '
        'RI_Correct
        '
        Me.RI_Correct.KeyTip = "C"
        Me.RI_Correct.Label = "Correct"
        Me.RI_Correct.Name = "RI_Correct"
        Me.RI_Correct.OfficeImageId = "SpellingAndGrammar"
        Me.RI_Correct.ScreenTip = "Will correct the selected text (clean and with a markup for visibility)"
        Me.RI_Correct.ShowImage = True
        '
        'Menu2
        '
        Me.Menu2.Items.Add(Me.RI_Improve)
        Me.Menu2.Items.Add(Me.RI_ApplyMyStyle)
        Me.Menu2.Items.Add(Me.RI_NoFillers)
        Me.Menu2.Items.Add(Me.RI_Friendly)
        Me.Menu2.Items.Add(Me.RI_Convincing)
        Me.Menu2.Label = "Improve"
        Me.Menu2.Name = "Menu2"
        Me.Menu2.OfficeImageId = "Drawing1GalleryBrightness"
        Me.Menu2.ScreenTip = "Improve your text in various ways"
        Me.Menu2.ShowImage = True
        '
        'RI_Improve
        '
        Me.RI_Improve.Label = "Improve"
        Me.RI_Improve.Name = "RI_Improve"
        Me.RI_Improve.OfficeImageId = "Drawing1GalleryBrightness"
        Me.RI_Improve.ScreenTip = "Will improve the selected text"
        Me.RI_Improve.ShowImage = True
        '
        'RI_ApplyMyStyle
        '
        Me.RI_ApplyMyStyle.Label = "Apply MyStyle"
        Me.RI_ApplyMyStyle.Name = "RI_ApplyMyStyle"
        Me.RI_ApplyMyStyle.OfficeImageId = "ControlWizards"
        Me.RI_ApplyMyStyle.ScreenTip = "Apply a MyStyle prompt to your text"
        Me.RI_ApplyMyStyle.ShowImage = True
        '
        'RI_NoFillers
        '
        Me.RI_NoFillers.Label = "No Filler Words"
        Me.RI_NoFillers.Name = "RI_NoFillers"
        Me.RI_NoFillers.OfficeImageId = "ReviewRejectChange"
        Me.RI_NoFillers.ScreenTip = "Remove filler words from your text"
        Me.RI_NoFillers.ShowImage = True
        '
        'RI_Friendly
        '
        Me.RI_Friendly.Label = "More Friendly"
        Me.RI_Friendly.Name = "RI_Friendly"
        Me.RI_Friendly.OfficeImageId = "SendCopyCheckNames"
        Me.RI_Friendly.ScreenTip = "Make your text more friendly"
        Me.RI_Friendly.ShowImage = True
        '
        'RI_Convincing
        '
        Me.RI_Convincing.Label = "More Convincing"
        Me.RI_Convincing.Name = "RI_Convincing"
        Me.RI_Convincing.OfficeImageId = "SendContactMenu"
        Me.RI_Convincing.ScreenTip = "Make your text more convincing"
        Me.RI_Convincing.ShowImage = True
        '
        'RI_Shorten
        '
        Me.RI_Shorten.Label = "Shorten"
        Me.RI_Shorten.Name = "RI_Shorten"
        Me.RI_Shorten.OfficeImageId = "Cut"
        Me.RI_Shorten.ScreenTip = "Will shorten the selected text"
        Me.RI_Shorten.ShowImage = True
        '
        'RI_Summarize
        '
        Me.RI_Summarize.Label = "Summarize"
        Me.RI_Summarize.Name = "RI_Summarize"
        Me.RI_Summarize.OfficeImageId = "ArrangeByAvailability"
        Me.RI_Summarize.ScreenTip = "Will create a short summary of your selected text"
        Me.RI_Summarize.ShowImage = True
        '
        'Sumup
        '
        Me.Sumup.Label = "Sum-up"
        Me.Sumup.Name = "Sumup"
        Me.Sumup.OfficeImageId = "MessageDeliveryInformation"
        Me.Sumup.ScreenTip = "Will create a summary of the mail chain"
        Me.Sumup.ShowImage = True
        '
        'RI_Answers
        '
        Me.RI_Answers.KeyTip = "A"
        Me.RI_Answers.Label = "Reply"
        Me.RI_Answers.Name = "RI_Answers"
        Me.RI_Answers.OfficeImageId = "Reply"
        Me.RI_Answers.ScreenTip = "Will draft an answer according to the e-mail chain parts you have selected"
        Me.RI_Answers.ShowImage = True
        '
        'RI_Freestyle
        '
        Me.RI_Freestyle.Label = "Freestyle"
        Me.RI_Freestyle.Name = "RI_Freestyle"
        Me.RI_Freestyle.OfficeImageId = "CustomActionsGallery"
        Me.RI_Freestyle.ScreenTip = "Allows you to to enter a prompt and get the result, based on selected text or wit" &
    "hout a text"
        Me.RI_Freestyle.ShowImage = True
        '
        'RI_Clipboard
        '
        Me.RI_Clipboard.Label = "Clipboard to Text"
        Me.RI_Clipboard.Name = "RI_Clipboard"
        Me.RI_Clipboard.OfficeImageId = "ConvertInkMenu"
        Me.RI_Clipboard.ScreenTip = "Will convert to text what is contained in the clipboard (e.g., screenshot, video, " &
    "audio, image)"
        Me.RI_Clipboard.ShowImage = True
        '
        'RI_DefineMyStyle
        '
        Me.RI_DefineMyStyle.Label = "Define MyStyle"
        Me.RI_DefineMyStyle.Name = "RI_DefineMyStyle"
        Me.RI_DefineMyStyle.OfficeImageId = "DisplayForm"
        Me.RI_DefineMyStyle.ScreenTip = "Analyze your writing style and create a MyStyle prompt based on it"
        Me.RI_DefineMyStyle.ShowImage = True
        '
        'Settings
        '
        Me.Settings.Label = "Settings"
        Me.Settings.Name = "Settings"
        Me.Settings.OfficeImageId = "SetupClassicOffline"
        Me.Settings.ScreenTip = "Allows you to temporarily change the settings"
        Me.Settings.ShowImage = True
        '
        'Group2
        '
        Me.Group2.Items.Add(Me.RI_PrimLang2)
        Me.Group2.Items.Add(Me.RI_Correct2)
        Me.Group2.Items.Add(Me.Sumup2)
        Me.Group2.KeyTip = "R"
        Me.Group2.Label = "Red Ink"
        Me.Group2.Name = "Group2"
        Me.Group2.Position = Me.Factory.RibbonPosition.AfterOfficeId("GroupNames")
        '
        'RI_PrimLang2
        '
        Me.RI_PrimLang2.KeyTip = "E"
        Me.RI_PrimLang2.Label = "English"
        Me.RI_PrimLang2.Name = "RI_PrimLang2"
        Me.RI_PrimLang2.OfficeImageId = "TranslateMenu"
        Me.RI_PrimLang2.ScreenTip = "Will translate the selected text"
        Me.RI_PrimLang2.ShowImage = True
        '
        'RI_Correct2
        '
        Me.RI_Correct2.KeyTip = "C"
        Me.RI_Correct2.Label = "Correct"
        Me.RI_Correct2.Name = "RI_Correct2"
        Me.RI_Correct2.OfficeImageId = "SpellingAndGrammar"
        Me.RI_Correct2.ScreenTip = "Will correct the selected text (clean and with a markup for visibility)"
        Me.RI_Correct2.ShowImage = True
        '
        'Sumup2
        '
        Me.Sumup2.Label = "Sum-up"
        Me.Sumup2.Name = "Sumup2"
        Me.Sumup2.OfficeImageId = "MessageDeliveryInformation"
        Me.Sumup2.ScreenTip = "Will create a summary of the mail chain"
        Me.Sumup2.ShowImage = True
        '
        'Ribbon1
        '
        Me.Name = "Ribbon1"
        Me.RibbonType = "Microsoft.Outlook.Mail.Compose"
        Me.Tabs.Add(Me.Tab1)
        Me.Tab1.ResumeLayout(False)
        Me.Tab1.PerformLayout()
        Me.Group1.ResumeLayout(False)
        Me.Group1.PerformLayout()
        Me.Group2.ResumeLayout(False)
        Me.Group2.PerformLayout()
        Me.ResumeLayout(False)

    End Sub

    Private Async Sub Ribbon1_Load(ByVal sender As Object, ByVal e As RibbonUIEventArgs) Handles MyBase.Load

    End Sub


    Public Async Function UpdateRibbon() As Task

        If String.IsNullOrWhiteSpace(ThisAddIn.INI_APICall_Object) Then
            Me.RI_Clipboard.Visible = False
        Else
            Me.RI_Clipboard.Visible = True
        End If

        Me.RI_Primlang.Label = ThisAddIn.INI_Language1 'primlang
        Me.RI_PrimLang2.Label = ThisAddIn.INI_Language1 'primlang        
        Me.Menu1.ScreenTip = If(String.IsNullOrEmpty(ThisAddIn.INI_UsageRestrictions), "",
                            ThisAddIn.INI_UsageRestrictions)
        Me.Menu1.SuperTip = AN & " " & ThisAddIn.Version &
                        " © by David Rosenthal, VISCHER AG " &
                        "(model: " & ThisAddIn.INI_Model & ")"

        If Trim(ThisAddIn.INI_MyStylePath) = "" Then
            Me.RI_DefineMyStyle.Visible = False
            Me.RI_ApplyMyStyle.Visible = False
        Else
            Me.RI_DefineMyStyle.Visible = True
            Me.RI_ApplyMyStyle.Visible = True
        End If

    End Function



    Friend WithEvents Tab1 As RibbonTab
    Friend WithEvents Group1 As RibbonGroup
    Friend WithEvents RI_Correct As RibbonButton
    Friend WithEvents Menu1 As RibbonMenu
    Friend WithEvents RI_Answers As RibbonButton
    Friend WithEvents RI_Shorten As RibbonButton
    Friend WithEvents RI_Summarize As RibbonButton
    Friend WithEvents RI_Freestyle As RibbonButton
    Friend WithEvents RI_Clipboard As RibbonButton
    Friend WithEvents RI_Translate As RibbonButton
    Friend WithEvents RI_Primlang As RibbonButton
    Friend WithEvents Group2 As RibbonGroup
    Friend WithEvents RI_PrimLang2 As RibbonButton
    Friend WithEvents RI_Correct2 As RibbonButton
    Friend WithEvents Settings As RibbonButton
    Friend WithEvents Sumup As RibbonButton
    Friend WithEvents Sumup2 As RibbonButton
    Friend WithEvents Menu2 As RibbonMenu
    Friend WithEvents RI_Improve As RibbonButton
    Friend WithEvents RI_NoFillers As RibbonButton
    Friend WithEvents RI_Friendly As RibbonButton
    Friend WithEvents RI_Convincing As RibbonButton
    Friend WithEvents RI_ApplyMyStyle As RibbonButton
    Friend WithEvents RI_DefineMyStyle As RibbonButton
End Class

Partial Class ThisRibbonCollection

    <System.Diagnostics.DebuggerNonUserCode()>
    Friend ReadOnly Property Ribbon1() As Ribbon1
        Get
            Return Me.GetRibbon(Of Ribbon1)()
        End Get
    End Property
End Class



Partial Class Ribbon2
    Inherits RibbonBase

    <System.Diagnostics.DebuggerNonUserCode()>
    Public Sub New(ByVal container As System.ComponentModel.IContainer)
        MyClass.New()

        'Required for Windows.Forms Class Composition Designer support
        If (container IsNot Nothing) Then
            container.Add(Me)
        End If

    End Sub

    <System.Diagnostics.DebuggerNonUserCode()>
    Public Sub New()
        MyBase.New(Globals.Factory.GetRibbonFactory())

        'This call is required by the Component Designer.
        InitializeComponent()

    End Sub

    'Component overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Component Designer
    Private components As System.ComponentModel.IContainer

    Public AN As String = "Red Ink" ' Also Search & Replace manually

    'NOTE: The following procedure is required by the Component Designer
    'It can be modified using the Component Designer.
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Me.Tab1 = Me.Factory.CreateRibbonTab
        Me.Group1 = Me.Factory.CreateRibbonGroup
        Me.Menu1 = Me.Factory.CreateRibbonMenu
        Me.RI_Primlang = Me.Factory.CreateRibbonButton
        Me.RI_Translate = Me.Factory.CreateRibbonButton
        Me.RI_Correct = Me.Factory.CreateRibbonButton
        Me.Menu2 = Me.Factory.CreateRibbonMenu
        Me.RI_Improve = Me.Factory.CreateRibbonButton
        Me.RI_ApplyMyStyle = Me.Factory.CreateRibbonButton
        Me.RI_NoFillers = Me.Factory.CreateRibbonButton
        Me.RI_Friendly = Me.Factory.CreateRibbonButton
        Me.RI_Convincing = Me.Factory.CreateRibbonButton
        Me.RI_Shorten = Me.Factory.CreateRibbonButton
        Me.RI_Summarize = Me.Factory.CreateRibbonButton
        Me.Sumup = Me.Factory.CreateRibbonButton
        Me.RI_Answers = Me.Factory.CreateRibbonButton
        Me.RI_Freestyle = Me.Factory.CreateRibbonButton
        Me.RI_Clipboard = Me.Factory.CreateRibbonButton
        Me.RI_DefineMyStyle = Me.Factory.CreateRibbonButton
        Me.Settings = Me.Factory.CreateRibbonButton
        Me.Group2 = Me.Factory.CreateRibbonGroup
        Me.RI_PrimLang2 = Me.Factory.CreateRibbonButton
        Me.RI_Correct2 = Me.Factory.CreateRibbonButton
        Me.Sumup2 = Me.Factory.CreateRibbonButton
        Me.Tab1.SuspendLayout()
        Me.Group1.SuspendLayout()
        Me.Group2.SuspendLayout()
        Me.SuspendLayout()
        '
        'Tab1
        '
        Me.Tab1.ControlId.ControlIdType = Microsoft.Office.Tools.Ribbon.RibbonControlIdType.Office
        Me.Tab1.ControlId.OfficeId = "TabMail"
        Me.Tab1.Groups.Add(Me.Group1)
        Me.Tab1.Groups.Add(Me.Group2)
        Me.Tab1.Label = "TabMail"
        Me.Tab1.Name = "Tab1"
        '
        'Group1
        '
        Me.Group1.Items.Add(Me.Menu1)
        Me.Group1.KeyTip = "R"
        Me.Group1.Label = "Red Ink"
        Me.Group1.Name = "Group1"
        Me.Group1.Position = Me.Factory.RibbonPosition.AfterOfficeId("GroupNames")
        '
        'Menu1
        '
        Me.Menu1.ControlSize = Microsoft.Office.Core.RibbonControlSize.RibbonControlSizeLarge
        Me.Menu1.Image = Global.Red_Ink_for_Outlook.My.Resources.Resources.Red_Ink_Logo
        Me.Menu1.Items.Add(Me.RI_Primlang)
        Me.Menu1.Items.Add(Me.RI_Translate)
        Me.Menu1.Items.Add(Me.RI_Correct)
        Me.Menu1.Items.Add(Me.Menu2)
        Me.Menu1.Items.Add(Me.RI_Shorten)
        Me.Menu1.Items.Add(Me.RI_Summarize)
        Me.Menu1.Items.Add(Me.Sumup)
        Me.Menu1.Items.Add(Me.RI_Answers)
        Me.Menu1.Items.Add(Me.RI_Freestyle)
        Me.Menu1.Items.Add(Me.RI_Clipboard)
        Me.Menu1.Items.Add(Me.RI_DefineMyStyle)
        Me.Menu1.Items.Add(Me.Settings)
        Me.Menu1.KeyTip = "S"
        Me.Menu1.Label = "Task"
        Me.Menu1.Name = "Menu1"
        Me.Menu1.ShowImage = True
        Me.Menu1.SuperTip = "Access other functions of Red Ink"
        '
        'RI_Primlang
        '
        Me.RI_Primlang.KeyTip = "E"
        Me.RI_Primlang.Label = "English"
        Me.RI_Primlang.Name = "RI_Primlang"
        Me.RI_Primlang.OfficeImageId = "TranslateMenu"
        Me.RI_Primlang.ScreenTip = "Will translate the selected text"
        Me.RI_Primlang.ShowImage = True
        '
        'RI_Translate
        '
        Me.RI_Translate.Label = "Translate"
        Me.RI_Translate.Name = "RI_Translate"
        Me.RI_Translate.OfficeImageId = "TranslateMenu"
        Me.RI_Translate.ScreenTip = "Translates the selected text into a language you choose"
        Me.RI_Translate.ShowImage = True
        '
        'RI_Correct
        '
        Me.RI_Correct.KeyTip = "C"
        Me.RI_Correct.Label = "Correct"
        Me.RI_Correct.Name = "RI_Correct"
        Me.RI_Correct.OfficeImageId = "SpellingAndGrammar"
        Me.RI_Correct.ScreenTip = "Will correct the selected text (clean and with a markup for visibility)"
        Me.RI_Correct.ShowImage = True
        '
        'Menu2
        '
        Me.Menu2.Items.Add(Me.RI_Improve)
        Me.Menu2.Items.Add(Me.RI_ApplyMyStyle)
        Me.Menu2.Items.Add(Me.RI_NoFillers)
        Me.Menu2.Items.Add(Me.RI_Friendly)
        Me.Menu2.Items.Add(Me.RI_Convincing)
        Me.Menu2.Label = "Improve"
        Me.Menu2.Name = "Menu2"
        Me.Menu2.OfficeImageId = "Drawing1GalleryBrightness"
        Me.Menu2.ScreenTip = "Improve your text in various ways"
        Me.Menu2.ShowImage = True
        '
        'RI_Improve
        '
        Me.RI_Improve.Label = "Improve"
        Me.RI_Improve.Name = "RI_Improve"
        Me.RI_Improve.OfficeImageId = "Drawing1GalleryBrightness"
        Me.RI_Improve.ScreenTip = "Will improve the selected text"
        Me.RI_Improve.ShowImage = True
        '
        'RI_ApplyMyStyle
        '
        Me.RI_ApplyMyStyle.Label = "Apply MyStyle"
        Me.RI_ApplyMyStyle.Name = "RI_ApplyMyStyle"
        Me.RI_ApplyMyStyle.OfficeImageId = "ControlWizards"
        Me.RI_ApplyMyStyle.ScreenTip = "Apply a MyStyle prompt to your text"
        Me.RI_ApplyMyStyle.ShowImage = True
        '
        'RI_NoFillers
        '
        Me.RI_NoFillers.Label = "No Filler Words"
        Me.RI_NoFillers.Name = "RI_NoFillers"
        Me.RI_NoFillers.OfficeImageId = "ReviewRejectChange"
        Me.RI_NoFillers.ScreenTip = "Remove filler words from your text"
        Me.RI_NoFillers.ShowImage = True
        '
        'RI_Friendly
        '
        Me.RI_Friendly.Label = "More Friendly"
        Me.RI_Friendly.Name = "RI_Friendly"
        Me.RI_Friendly.OfficeImageId = "SendCopyCheckNames"
        Me.RI_Friendly.ScreenTip = "Make your text more friendly"
        Me.RI_Friendly.ShowImage = True
        '
        'RI_Convincing
        '
        Me.RI_Convincing.Label = "More Convincing"
        Me.RI_Convincing.Name = "RI_Convincing"
        Me.RI_Convincing.OfficeImageId = "SendContactMenu"
        Me.RI_Convincing.ScreenTip = "Make your text more convincing"
        Me.RI_Convincing.ShowImage = True
        '
        'RI_Shorten
        '
        Me.RI_Shorten.Label = "Shorten"
        Me.RI_Shorten.Name = "RI_Shorten"
        Me.RI_Shorten.OfficeImageId = "Cut"
        Me.RI_Shorten.ScreenTip = "Will shorten the selected text"
        Me.RI_Shorten.ShowImage = True
        '
        'RI_Summarize
        '
        Me.RI_Summarize.Label = "Summarize"
        Me.RI_Summarize.Name = "RI_Summarize"
        Me.RI_Summarize.OfficeImageId = "ArrangeByAvailability"
        Me.RI_Summarize.ScreenTip = "Will create a short summary of your selected text"
        Me.RI_Summarize.ShowImage = True
        '
        'Sumup
        '
        Me.Sumup.Label = "Sum-up"
        Me.Sumup.Name = "Sumup"
        Me.Sumup.OfficeImageId = "MessageDeliveryInformation"
        Me.Sumup.ScreenTip = "Will create a summary of the mail chain"
        Me.Sumup.ShowImage = True
        '
        'RI_Answers
        '
        Me.RI_Answers.KeyTip = "A"
        Me.RI_Answers.Label = "Reply"
        Me.RI_Answers.Name = "RI_Answers"
        Me.RI_Answers.OfficeImageId = "Reply"
        Me.RI_Answers.ScreenTip = "Will draft an answer according to the e-mail chain parts you have selected"
        Me.RI_Answers.ShowImage = True
        '
        'RI_Freestyle
        '
        Me.RI_Freestyle.Label = "Freestyle"
        Me.RI_Freestyle.Name = "RI_Freestyle"
        Me.RI_Freestyle.OfficeImageId = "CustomActionsGallery"
        Me.RI_Freestyle.ScreenTip = "Allows you to to enter a prompt and get the result, based on selected text or wit" &
    "hout a text"
        Me.RI_Freestyle.ShowImage = True
        '
        'RI_Clipboard
        '
        Me.RI_Clipboard.Label = "Clipboard to Text"
        Me.RI_Clipboard.Name = "RI_Clipboard"
        Me.RI_Clipboard.OfficeImageId = "ConvertInkMenu"
        Me.RI_Clipboard.ScreenTip = "Will convert to text what is contained in the clipboard (e.g., screenshot, video, " &
    "audio, image)"
        Me.RI_Clipboard.ShowImage = True
        '
        'RI_DefineMyStyle
        '
        Me.RI_DefineMyStyle.Label = "Define MyStyle"
        Me.RI_DefineMyStyle.Name = "RI_DefineMyStyle"
        Me.RI_DefineMyStyle.OfficeImageId = "DisplayForm"
        Me.RI_DefineMyStyle.ScreenTip = "Analyze your writing style and create a MyStyle prompt based on it"
        Me.RI_DefineMyStyle.ShowImage = True
        '
        'Settings
        '
        Me.Settings.Label = "Settings"
        Me.Settings.Name = "Settings"
        Me.Settings.OfficeImageId = "SetupClassicOffline"
        Me.Settings.ScreenTip = "Allows you to temporarily change the settings"
        Me.Settings.ShowImage = True
        '
        'Group2
        '
        Me.Group2.Items.Add(Me.RI_PrimLang2)
        Me.Group2.Items.Add(Me.RI_Correct2)
        Me.Group2.Items.Add(Me.Sumup2)
        Me.Group2.KeyTip = "R"
        Me.Group2.Label = "Red Ink"
        Me.Group2.Name = "Group2"
        Me.Group2.Position = Me.Factory.RibbonPosition.AfterOfficeId("GroupNames")
        '
        'RI_PrimLang2
        '
        Me.RI_PrimLang2.KeyTip = "E"
        Me.RI_PrimLang2.Label = "English"
        Me.RI_PrimLang2.Name = "RI_PrimLang2"
        Me.RI_PrimLang2.OfficeImageId = "TranslateMenu"
        Me.RI_PrimLang2.ScreenTip = "Will translate the selected text"
        Me.RI_PrimLang2.ShowImage = True
        '
        'RI_Correct2
        '
        Me.RI_Correct2.KeyTip = "C"
        Me.RI_Correct2.Label = "Correct"
        Me.RI_Correct2.Name = "RI_Correct2"
        Me.RI_Correct2.OfficeImageId = "SpellingAndGrammar"
        Me.RI_Correct2.ScreenTip = "Will correct the selected text (clean and with a markup for visibility)"
        Me.RI_Correct2.ShowImage = True
        '
        'Sumup2
        '
        Me.Sumup2.Label = "Sum-up"
        Me.Sumup2.Name = "Sumup2"
        Me.Sumup2.OfficeImageId = "MessageDeliveryInformation"
        Me.Sumup2.ScreenTip = "Will create a summary of the mail chain"
        Me.Sumup2.ShowImage = True
        '
        'Ribbon2
        '
        Me.Name = "Ribbon2"
        Me.RibbonType = "Microsoft.Outlook.Explorer"
        Me.Tabs.Add(Me.Tab1)
        Me.Tab1.ResumeLayout(False)
        Me.Tab1.PerformLayout()
        Me.Group1.ResumeLayout(False)
        Me.Group1.PerformLayout()
        Me.Group2.ResumeLayout(False)
        Me.Group2.PerformLayout()
        Me.ResumeLayout(False)

    End Sub

    Private Async Sub Ribbon2_Load(ByVal sender As Object, ByVal e As RibbonUIEventArgs) Handles MyBase.Load
        ' This is not necessary, but can be used for additional functions related to the ribbon itself

    End Sub


    Public Async Function UpdateRibbon() As Task

        If String.IsNullOrWhiteSpace(ThisAddIn.INI_APICall_Object) Then
            Me.RI_Clipboard.Visible = False
        Else
            Me.RI_Clipboard.Visible = True
        End If

        Me.RI_Primlang.Label = ThisAddIn.INI_Language1 'primlang
        Me.RI_PrimLang2.Label = ThisAddIn.INI_Language1 'primlang
        Me.Menu1.ScreenTip = If(String.IsNullOrEmpty(ThisAddIn.INI_UsageRestrictions), "",
        ThisAddIn.INI_UsageRestrictions)
        Me.Menu1.SuperTip = AN & " " & ThisAddIn.Version &
        " © by David Rosenthal, VISCHER AG " &
        "(model: " & ThisAddIn.INI_Model & ")"

        If Trim(ThisAddIn.INI_MyStylePath) = "" Then
            Me.RI_DefineMyStyle.Visible = False
            Me.RI_ApplyMyStyle.Visible = False
        Else
            Me.RI_DefineMyStyle.Visible = True
            Me.RI_ApplyMyStyle.Visible = True
        End If


    End Function



    Friend WithEvents Tab1 As RibbonTab
    Friend WithEvents Group1 As RibbonGroup
    Friend WithEvents RI_Correct As RibbonButton
    Friend WithEvents Menu1 As RibbonMenu
    Friend WithEvents RI_Answers As RibbonButton
    Friend WithEvents RI_Shorten As RibbonButton
    Friend WithEvents RI_Summarize As RibbonButton
    Friend WithEvents RI_Freestyle As RibbonButton
    Friend WithEvents RI_Clipboard As RibbonButton
    Friend WithEvents RI_Translate As RibbonButton
    Friend WithEvents RI_Primlang As RibbonButton
    Friend WithEvents Group2 As RibbonGroup
    Friend WithEvents RI_PrimLang2 As RibbonButton
    Friend WithEvents RI_Correct2 As RibbonButton
    Friend WithEvents Settings As RibbonButton
    Friend WithEvents Sumup As RibbonButton
    Friend WithEvents Sumup2 As RibbonButton
    Friend WithEvents Menu2 As RibbonMenu
    Friend WithEvents RI_Improve As RibbonButton
    Friend WithEvents RI_NoFillers As RibbonButton
    Friend WithEvents RI_Friendly As RibbonButton
    Friend WithEvents RI_Convincing As RibbonButton
    Friend WithEvents RI_ApplyMyStyle As RibbonButton
    Friend WithEvents RI_DefineMyStyle As RibbonButton
End Class

Partial Class ThisRibbonCollection
    <System.Diagnostics.DebuggerNonUserCode()>
    Friend ReadOnly Property Ribbon2() As Ribbon2
        Get
            Return Me.GetRibbon(Of Ribbon2)()
        End Get
    End Property
End Class
